### ISSUE TITLE
Traces can have configurable sampling

### ISSUE THREAD

**Issue by coolwednesday** [gofr-dev/gofr#1058]

**Comment by vipul-rawat** [comment]
This issue created a new problem where the traceID is not getting initialized, when tracer configs are not provided the global tracer becomes noop tracer

**Comment by aryanmehrotra** [comment]
@vipul-rawat should we create a new issue for the same and track it there

**Comment by vipul-rawat** [comment]
Sure! we can and then link it to this, will close this one!
