### ISSUE TITLE
Do not hide underlaying request

### ISSUE THREAD

**Issue by ArFnds** [gofr-dev/gofr#1066]
**Describe the bug**
I want to write a route that accepts a request of type `application/x-www-form-urlencoded`, and I found no way to get the binary data contained in the body.

IMHO, It's a really bad idea to fully encapsulate the original request, as such behaviour became just impossible to handle.

**To Reproduce**
- Receive a POST request of type `application/x-www-form-urlencoded`
- See that there is no way to bind or to get raw body
- cry, and open an issue

**Expected behavior**
A way to read the raw body.

**Screenshots**
-

**Environments (please complete the following information):**
- OS: linux/amd64
- gofr version 1.21.0
- go version 1.22

**More description**

**Comment by aryanmehrotra** [comment]
@ArFnds thanks for pointing this out, we will add support for it how multipart form is supported.

**Comment by Umang01-hash** [comment]
@ArFnds we have added the support for the Binding requests of type `application/x-www-form-urlencoded`.

You can find the implemented solution here : https://github.com/gofr-dev/gofr/pull/1073

**Comment by ArFnds** [comment]
Great ! Thank you.

Though the body is still hidden :/

**Comment by Umang01-hash** [comment]
@ArFnds i understand your concern. While we provide the support for directly binding the request body to respective type, currently we don't provide a direct access to request's body.

I hope you can use the `Bind` method to satisfy your needs, but if not please tell about more about your use-case

**Comment by ArFnds** [comment]
@Umang01-hash Here is my use-case:
```ts
function doSomething(apiClient: Axios, blob: Blob) {
	return apiClient
	      .post("/v1/dosomething", blob, {
	        params: {
	          filename,
	          mimeType,
	          language,
	        }
	      });
}
```
On the backend side, I receive this request (I skipped non relevant headers):
```http
POST /v1/transcribe?filename=myfilename.mp4&mimeType=audio%2Fmp3&language=en HTTP/1.1
Accept: application/json, text/plain, */*
Content-Length: 161270
Content-Type: application/x-www-form-urlencoded

[Here the raw blob goes]
```

Maybe the use of the `application/x-www-form-urlencoded` is not correct (axios does it), but I think the raw body should not be hidden, because it blocks the users of the framework for such manipulations.

**Comment by Umang01-hash** [comment]
Hi @ArFnds,

Thanks for sharing your use case!

- We avoid exposing the raw request body directly because it can lead to issues like resource leaks when the body isn’t closed properly after reading. By using structured methods like Bind, we ensure safer handling.

- For uploading files or binary data, `application/x-www-form-urlencoded` isn’t the recommended content type. Using `multipart/form-data`  would be more appropriate and secure.
