### ISSUE TITLE
Ping Function in Redis panics when called without being connected to redis in application

### ISSUE THREAD

**Issue by coolwednesday** [gofr-dev/gofr#1078]
**Describe the bug**
I tried running the http-server example and if redis is not connected and we try to call Redis.Ping() , it results in panic and exits the apllication

**To Reproduce**
Run the application without connecting database and providing redis configuration. 
Hit the trace endpoint.

The error is

   
<img width="956" alt="Screenshot 2024-10-04 at 3 59 52 PM" src="https://github.com/user-attachments/assets/125857b1-24bc-496d-acc0-7b78dc3baa24">

**Expected behavior**
Error log and no panic

**Comment by vigneshp91** [comment]
Can you assign this to me? @coolwednesday

**Comment by Umang01-hash** [comment]
Sure @vigneshp91. Assigned to you.
