### ISSUE TITLE
Invalid Cassandra godocs 

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#1080]
godocs is selecting docs from the mocks generated, should be proper.

Along with this re-verify the other go-docs comments present in the package

https://pkg.go.dev/gofr.dev/pkg/gofr/datasource/cassandra

<img width="462" alt="Screenshot 2024-10-04 at 7 04 33 PM" src="https://github.com/user-attachments/assets/46619626-47a9-4be5-9098-84b2df58804d">

**Comment by FilledEther20** [comment]
@aryanmehrotra Greetings Sir Could u assign this issue to me?

**Comment by aryanmehrotra** [comment]
We can assign one issue at a time to you, once the other issue is done let us know we will assign
