### ISSUE TITLE
Invalid Clickhouse godocs

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#1081]
godocs is selecting docs from the mocks generated, should be proper.

Along with this re-verify the other go-docs comments present in the package

https://pkg.go.dev/gofr.dev/pkg/gofr/datasource/clickhouse

<img width="469" alt="Screenshot 2024-10-04 at 7 06 03 PM" src="https://github.com/user-attachments/assets/e4be6535-a5da-4daa-9482-8a6b4697a3c7">

**Comment by Amalearner** [comment]
Hello, I'm interested in this issue but I can't seem to see the screenshot you're referring to.

**Comment by aryanmehrotra** [comment]
Can you try checking now

**Comment by FilledEther20** [comment]
@aryanmehrotra If this issue is still open could you assign this to me?
