### ISSUE TITLE
Invalid FTP godocs

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#1082]
godocs is selecting docs from the mocks generated, should be proper.

Along with this re-verify the other go-docs comments present in the package

https://pkg.go.dev/gofr.dev/pkg/gofr/datasource/file/ftp
<img width="429" alt="Screenshot 2024-10-04 at 7 08 09 PM" src="https://github.com/user-attachments/assets/21497c3b-db9b-4d3b-a6e4-5c48cf9a5b49">

**Comment by FilledEther20** [comment]
@aryanmehrotra Greetings Sir, Could you assign this issue to me ?
