### ISSUE TITLE
Infrastructure to build OAuth 2.0 Authorization and OpenID Connect (OIDC) standards

### ISSUE THREAD

**Issue by RahulMohanK** [gofr-dev/gofr#1083]
**Is your feature request related to a problem? Please describe.**
Recently I tried to build an authorization server using Go.Fr and it worked. The underlying standard for building auth server is based on OAuth2.0 and OIDC. Any developer who tries to build a standalone authorization server will have separately implement the same thing again.

**Describe the solution you'd like**
I propose a solution where Go.Fr inherently supports this feature from its main application. Users should be able to configure the OAuth2.0 and OIDC parameters and all necessary endpoints should be bootstrapped when the application starts, so that the developer only needs to focus on the configuration of the server and not on the underlying implementation.

**Additional context**
OAuth2.0 standards :
[RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-1)

**Comment by RahulMohanK** [comment]
I would like to implement the feature. Please share your thoughts and suggestion so that I could create a proper development plan for this.

**Comment by mfreeman451** [comment]
Can you share the repo? I am working on similar code.

**Comment by Umang01-hash** [comment]
Sure @RahulMohanK, you can proceed to implement this and raise a PR for the same. We can make it an optional parameter to integrate OIDC with OAuth such that users who want to use only OAuth should not be concerned much about it.

Integrating OAuth 2.0 Authorization and OpenID Connect (OIDC) standards into the GoFr framework is a great idea. It would significantly simplify the process for developers who need to build authorization servers, reducing the need for repetitive implementation.

**Comment by Umang01-hash** [comment]
> I would like to implement the feature. Please share your thoughts and suggestion.

Assigned the issue to you.

**Comment by vikash** [comment]
Does this mean that we are proposing that gofr application will have an oAuth server built-in? This looks like an overkill for most of the applications and can be considered as a separate project. In a microservice world, there is one auth server and multiple client services using the service.

**Comment by mfreeman451** [comment]
Why not build integrations for existing stuff like, auth0, google, keycloak, ory, etc? I personally am implementing ory right now in one of my own applications, I couldn't imagine recreating all of this from scratch...

**Comment by vipul-rawat** [comment]
Closing the issue on the note that in future provide and maintain integrations for different auth mechanisms.
