### ISSUE TITLE
Feature to fetch claims when authentication is enabled.

### ISSUE THREAD

**Issue by coolwednesday** [gofr-dev/gofr#1094]
**Is your feature request related to a problem? Please describe.**
We can have a feature to get claims from GoFr context ....no matter the kind of authentication we use. 

**Describe the solution you'd like**
The usecase can be generalized for various kind of authentication like jwt or api key etc .....

**Comment by coolwednesday** [comment]
@Umang01-hash , I would like to work on this issue. Please assign this to me.

**Comment by Umang01-hash** [comment]
Sure @coolwednesday. Assigning the issue to you.
