### ISSUE TITLE
how to return custom http response data and header 

### ISSUE THREAD

**Issue by brucke** [gofr-dev/gofr#1130]
Hey, 

I tried gofr for one of my Projects. I'm realy happy with it, but now I faced a big blocking point to continue with gofr. 

I want to return a custom http response. 

Data: string
And a lot of http headers

But at the moment I can't find the API to do it. I analyzed the source code and found the Responder and also the response.Raw and response.File but that's not sufficient. I have to add more custom headers. So only way I see at the moment is CustomMiddleware but from my point of view this feels wrong. 

Because it's not possible to attach a middleware to a dedicated route only globally. 

Has anybody a hit / idea for me?

**Comment by vipul-rawat** [comment]
Hey @brucke, can you please elaborate on the use case where and what response headers you want to send?

**Comment by brucke** [comment]
Hey, 
I generate calendar based on different settings which can be subscribe for instance by google calendar. 

for instance: 
```
	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%v.ics", childId))
	w.Header().Set("Cache-Control", "no-cache, no-store, max-age=0, must-revalidate")
	w.Header().Set("Content-Type", "text/calendar")
	w.Write([]byte(cal.Serialize()))
	w.WriteHeader(200)
```
And I have a plain text like: https://de.wikipedia.org/wiki/ICalendar

**Comment by vipul-rawat** [comment]
Hey @brucke, I understand your use case. We already have the `response.File` struct for returning file data, where you can set the content type. 
As for the `Content-Disposition` and `Cache-Control,` we can discuss the best way to support these and other required Headers.

**Comment by rigved-telang** [comment]
@vipul-rawat hey can you please assign this issue to me?

**Comment by rigved-telang** [comment]
Hey @vipul-rawat, I needed a little help, I am adding a new `response.go` to the `pkg/gofr/http/response` directory. Now during local development how do I import my local files instead of the remote package files. I am sorry I tried googling but am unable to find a solution, I tried using `replace gofr.dev/pkg/gofr => ./pkg/gofr` and even tried go workspace but was not able to do it. Can you please help

**Comment by brucke** [comment]
Thanks :) I try it today if it fits my needs.

**Comment by rigved-telang** [comment]
Hey @vipul-rawat, I needed a little help. I added a new `response.go` under the `pkg/gofr/http/response` directory, now I want to use my local files in another project to test if my functionality is working, how can i do that, I tried doing `replace gofr.dev/pkg/gofr => ../gofr/pkg/gofr` but that is not working.

**Comment by vipul-rawat** [comment]
Hey @rigved-telang, replace it until the first gofr folder
`gofr.dev => ../gofr`
You can replace only the module and not just one package.

**Comment by rigved-telang** [comment]
thanks, it worked

**Comment by rigved-telang** [comment]
And in the gofr repo itself, the replace line should be `replace gofr.dev => ./` right? Currently I had put the line as `replace gofr.dev/pkg/gofr => ./pkg/gofr` and that was working. I am sorry I am new to go hence the confusion.
