### ISSUE TITLE
[README] : I want to update the README for 'gofr'

### ISSUE THREAD

**Issue by abhirajadhikary06** [gofr-dev/gofr#1131]
**Describe the bug**
Actually it is not a bug but an request to update the README file.

**Expected Updates**
The current README for 'gofr' lacks clarity in certain sections and could benefit from additional details to improve user understanding. I propose to:

Add clear instructions for setting up the project.
Include usage examples for better comprehension.
Correct any outdated or incomplete information.
Ensure consistent formatting and structure throughout the document.
This update will enhance the overall readability and usability for both new and experienced users.

Being a newbie in OpenSource I am thinking of starting from here. Also keep me updated if any documentation updating is required.
@vipul-rawat Please assign me the issue

**Comment by Umang01-hash** [comment]
@abhirajadhikary06 assigned the issue to you

**Comment by abhirajadhikary06** [comment]
Thank you for assigning

**Comment by abhirajadhikary06** [comment]
@Umang01-hash I have initiated a PR please check.

**Comment by abhirajadhikary06** [comment]
@Umang01-hash Please review my task and if this seems okay please merge it.
