### ISSUE TITLE
Add support for binary/octet-stream in http/request.go Bind

### ISSUE THREAD

**Issue by vhodges** [gofr-dev/gofr#1143]
I have a need to access to the request.Body in it's raw []byte form for my application (clients will GET or POST an endpoint with a document included as the body). 

I see three potential ways that you might allow this:

1. provide a way to do Bind()ing using binary/octet-stream
2. simply expose a Body() method on Request.  
3. Provide way to register a custom route to App with a standard library Handler so that I can process it myself.

My only  other option right now is to use a  multipart/form-data with a file field, however this will complicate the client side considerably (imo) and would consider  porting away from gofr (which would be a shame since there's so much to like otherwise).

**Comment by coolwednesday** [comment]
Hi @vhodges,

Thank you for bringing this to our attention! You can expect it to be resolved in the upcoming release. Stay tuned for updates!
