### ISSUE TITLE
http server: add route groups

### ISSUE THREAD

**Issue by mfreeman451** [gofr-dev/gofr#1152]
**Is your feature request related to a problem? Please describe.**
Currently we lack the ability to group routes and apply middleware only to that group. The gofr team has informed me that it is their opinion that a new microservice should be created if it requires different middleware. I think that this is a broken pattern that unnecessarily demands users create additional microservices. For example, say you are creating an API with endpoints to create new users, and to login users, get user information, and so on. The newUser() routines would be gated perhaps by an API key only known to the admin/superuser, the login() endpoints should have no middleware yet, and the getUser() type endpoints would need middleware that only allows a logged in user and so on. This would require 3 different microservices.

**Describe the solution you'd like**
Nearly every other HTTP server you could use already supports this. We should have the ability to group routes and apply specific middlwares to them.

**Describe alternatives you've considered**
Stop using gofr for HTTP servers.

**Additional context**

**Comment by vipul-rawat** [comment]
Hey @mfreeman451 we at gofr are trying to optimize and keep microservice development as our forefront thought in all our development. Keeping that in mind the use case does not seem good enough/clear enough for us to support the feature as of now.
Thank you for letting us know your thoughts. We would still recommend doing 3 microservices as you would need at least 3 tables to handle this use case and one microservice should have access to one table.
