### ISSUE TITLE
Important | Support Configurable MySQL Charset 

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#1171]
Allowing the MySQL charset to be configurable in the application, currently, it is set to `utf8` we want to use `utf8mb4`
We have a requirement to store emojis in the database and by default `UTF8` supports up to 3 bytes for a character string which covers 90% of all Unicode characters, but utf8mb4, on the other hand, supports the entire Unicode character set, including emojis and other supplementary character.

https://github.com/gofr-dev/gofr/blob/366d3f5a1783d73d10353da48446793b27631f3d/pkg/gofr/datasource/sql/sql.go#L168

**Comment by surajit-zs** [comment]
I'd like to work on this.
Please assign me.

**Comment by Umang01-hash** [comment]
Sure @surajit-zs 
Assigned!
