### ISSUE TITLE
Support Sentry

### ISSUE THREAD

**Issue by Bermos** [gofr-dev/gofr#1181]
**Is your feature request related to a problem? Please describe.**
[Sentry.io](https://sentry.io/welcome/) is a growing platform to monitor the health and performance of a service. I think it would be a perfect fit for this framework and enhance the developers experience in staying on top of operations of their services.

**Describe the solution you'd like**
I would like to integrate the existing go SDK from sentry into this framework so that tracing transactions are automatically recorded, spans can be produced and metrics and errors are reportet to the sentry platform. I'd be willing to do that development but I'd like to have a general, we are ok with that, before I spend to much time on it.

**Describe alternatives you've considered**
It may be possible to create an integration in the official [sentry-go SDK](https://github.com/getsentry/sentry-go) for gofr, that would need some hooks into gofr to work if I understand that correctly. The transaction start would be easy by creating a middleware, if we want to be fancier with db profiling or instrumenting other gofr integrations there could be a lot of work.

**Additional context**
[Key Terms & Features](https://docs.sentry.io/concepts/key-terms/key-terms/) of Sentry.

**Comment by coolwednesday** [comment]
Hey @Bermos , has Sentry previously been integrated in other Golang frameworks ? If yes, what has been the approach among the above discussed two ?

**Comment by vikash** [comment]
Gofr already supports tracing. All transactions are already recorded in open telemetry format. Shipping to sentry is infrastructure level concern.
