### ISSUE TITLE
Support uuid in AddRestHandler

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#1187]
When a struct has fields of type int, string, bool those are supported for operations, we need to support uuid type as well.

**Comment by coolwednesday** [comment]
@aryanmehrotra , The uuid.UUID type can be used, but to ensure compatibility with the database, the id field should be defined as a CHAR(36) or VARCHAR(36) data type, rather than an INT, since UUIDs are stored as 36-character strings. This issue can now be considered resolved.
