### ISSUE TITLE
Detailed Logs for Static File Server

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#1229]
I tried adding a static file server, but I didn't get any logs when the path was wrong, and no endpoints were registered from the directory.

I would need to get inside the code and figure out that the path should start with `./`

May be `./` can be automatically added or Debug logs should be present to debug easier without going inside the code.

<img width="1234" alt="Screenshot 2024-11-20 at 12 10 35 PM" src="https://github.com/user-attachments/assets/ac5f8bcd-451b-4f27-acde-a888ac5cc74d">

**Comment by shashank-zopsmart** [comment]
Can you please tell the way to reproduce this issue as when I was trying with one of the examples present in Gofr repo, I got error level log

<img width="1596" alt="Screenshot 2024-11-20 at 7 23 16 PM" src="https://github.com/user-attachments/assets/2cd43003-7c40-4a7e-9e13-d6f121b25281">

**Comment by Umang01-hash** [comment]
@shashank-zopsmart as shown in the issue description you need to create a directory and then give it's path to our **app.AddStaticFiles** method.

**Comment by shashank-zopsmart** [comment]
@Umang01-hash I tried following scenarios:

- *Path (out), Directory (not present):* Got error log signifying that route was not registered
- *Path (./out), Directory (not present):* Got error log signifying that route was not registered
- *Path (out), Directory (present):* Everything worked fine
- *Path (./out), Directory (present):* Everything worked fine
