### ISSUE TITLE
Critical Issues with Solr Methods, Documentation, and Connection Handling

### ISSUE THREAD

**Issue by coolwednesday** [gofr-dev/gofr#1233]
Errors:

- Methods `Update`, `Delete`, `ListFields`,  `Retrieve`, `AddField`, `UpdateField`, `DeleteField` give error.
- Documentation needs to be updated.
- connection in Solr does not check for unsuccessful connection

**Comment by coolwednesday** [comment]
@Umang01-hash, please assign this issue to me.

**Comment by Umang01-hash** [comment]
@coolwednesday assigned!
