### ISSUE TITLE
Server shouldn't start if HTTP_PORT is blocked

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#1243]
If the HTTP_PORT is blocked the server should not start. Currently, it appears the server attempts to start even if the port is in use which can lead to issues.
This issue proposes that the server should perform a check before starting to ensure the HTTP_PORT is available. If the port is blocked, the server should fail to start and log an error message.
This enhancement will improve the reliability of the application and prevent unexpected behavior.

<img width="1306" alt="Screenshot 2024-11-27 at 11 40 53 AM" src="https://github.com/user-attachments/assets/6f97f8ff-d263-4dc0-aa94-218c1b991c7e">

**Comment by coolwednesday** [comment]
@Umang01-hash , please assign this issue to me.

**Comment by coolwednesday** [comment]
To address this issue, we should ensure that all required servers (gRPC, Pub/Sub, HTTP) are able to start successfully. If any of these servers fail to start, for example, due to a blocked port, we should shut down the entire application to maintain consistency and avoid partial availability.
