### ISSUE TITLE
Refactor unit tests with hardcoded ports

### ISSUE THREAD

**Issue by ccoVeille** [gofr-dev/gofr#1248]
The tests are using hardcoded port, it's not a good pattern. Unit tests cannot be launched in parallel.

Any of these packages could be used

https://github.com/facebookarchive/freeport
https://github.com/projectdiscovery/freeport
https://github.com/phayes/freeport
https://github.com/Konstantin8105/FreePort
https://github.com/jamielxcarter/dort
https://github.com/prithviramesh/free-port-finder

Of course, as the feature is very basic, it could be added via a simple helper. By copy pasting something like this.

https://gist.github.com/sevkin/96bdae9274465b2d09191384f86ef39d

From a library with a copyleft license

**Comment by vikash** [comment]
This is a great idea - whenever we are actually testing a call over a port.
