### ISSUE TITLE
Missing Check for Empty Topic

### ISSUE THREAD

**Issue by akshat-zopsmart** [gofr-dev/gofr#1257]
**Describe the bug**
Empty Topic in Subscription causing error in infinite loop

**To Reproduce**
Send empty topic in `app.Subscribe(topicName, handler)` 

The error is

   ```
{"level":"ERROR","time":"2024-11-29T11:54:45.036300197Z","message":"error while reading from topic , err: rpc error: code = InvalidArgument desc = Invalid resource name given (name=projects/zs-products/topics/). Refer to https://cloud.google.com/pubsub/docs/pubsub-basics#resource_names for more information.","gofrVersion":"v1.27.1"}   
   ```

**Expected behavior**
Should return error from the `app.Subscribe(topicName, handler)` method itself, similar to how it's returning for uninitialised pubSub connection.

**Comment by vikash** [comment]
Thanks for quick fix.
