### ISSUE TITLE
Disconnected Spans are exported to the remote-log-url

### ISSUE THREAD

**Issue by coolwednesday** [gofr-dev/gofr#1278]
**Describe the bug**
Disconnected spans are found when we set a remote-log-url

**Expected behavior**
It is necessary to Identify the connected spans and ensuring they have the same trace-id.

**Screenshots**
[
<img width="525" alt="Screenshot 2024-12-06 at 6 36 17 PM" src="https://github.com/user-attachments/assets/3560a4f6-b708-4fb3-a996-e79d7ac42d34">
](url)

**Comment by coolwednesday** [comment]
@Umang01-hash , please assign this issue to me.

**Comment by Umang01-hash** [comment]
@coolwednesday assigned the issue to you.
