### ISSUE TITLE
Nats Jetstream External Driver does not install

### ISSUE THREAD

**Issue by hasanerken** [gofr-dev/gofr#1281]
Hi, when try to install nats plugin it returns this error:

go get gofr.dev/pkg/gofr/datasource/pubsub/nats      
go: module gofr.dev@upgrade found (v1.28.1), but does not contain package gofr.dev/pkg/gofr/datasource/pubsub/nats

Gofr version: 1.28.1
Go version: 1.23.2

**Comment by aryanmehrotra** [comment]
The link on the website and the tag were missing - have added them now can you please check?

**Comment by hasanerken** [comment]
go get gofr.dev/pkg/gofr/datasources/pubsub/nats on this page (https://gofr.dev/docs/advanced-guide/using-publisher-subscriber) should be  go get gofr.dev/pkg/gofr/datasource/pubsub/nats
