### ISSUE TITLE
Redis gofr migration restriction to use centralised redis for multiple services

### ISSUE THREAD

**Issue by Shiv-zs** [gofr-dev/gofr#1289]
### Problem
Currently, when multiple services share a centralized Redis instance, managing Redis migrations across all services becomes challenging. The lack of service-specific separation for migrations leads to potential conflicts and maintenance overhead.

---

### Expected Behavior
Redis migrations should be independently manageable for each service, even when using a shared Redis instance.

---

### Proposed Solution
Introduce an `APP_NAME` configuration for each service. The framework will create and manage a dedicated `gofr_migrations` table in Redis for each service, based on the provided `APP_NAME`. This approach ensures migration operations are scoped to the respective service.

---

## Additional Context
- This enhancement will simplify the management of Redis migrations in microservice architectures where services share a Redis instance.
- It aligns with the principles of service independence, ensuring migration scripts are isolated.

**Comment by aryanmehrotra** [comment]
Yeah that seems to be a nice way - we will create sets of the form - APP-NAME_gofr_migrations.

Such that it does not collide with other migrations

**Comment by aryanmehrotra** [comment]
There is an option in redis to connect to a different database of a same instance similar to SQL databases. Which is currently not supported in gofr(we can explore more if that should be an infra level concern) but why are we not using it like that?

Moreover, it is recommended way of doing it, can you please take a look.

Select command lets you change it.
https://redis.io/docs/latest/commands/select/

<img width="1043" alt="Screenshot 2024-12-10 at 4 22 31 PM" src="https://github.com/user-attachments/assets/cb27173a-693f-402a-b508-2f4b9349b899">

**Comment by Shiv-zs** [comment]
Yes that would solve the problem, if we can add the support to change redis database.

**Comment by aryanmehrotra** [comment]
If gofr_migration already exists in your database, you would need to change the name.
And every microservice should have their own database instead of using one database.
