### ISSUE TITLE
HTTP Handler - not able to set path param while testing

### ISSUE THREAD

**Issue by PiyushSingh-ZS** [gofr-dev/gofr#1305]
**Describe the bug**
Have added a route with path param 
	app.POST("/environments/{id}/deploymentspace", deploymentHandler.Add)

while writing test cases for the Handler function, i am not able to pass path param

**Expected behavior**
Should be able to set path param in gofr context while writing test cases

<img width="741" alt="image" src="https://github.com/user-attachments/assets/749e82a0-940f-4f7e-9714-b3a2531a2555" />

**Environments (please complete the following information):**
- OS: MacOs
- gofr version v1.28.0
- go version 1.22.8

**Comment by vipul-rawat** [comment]
Hey @PiyushSingh-ZS You are using httptest.NewRequest which returns a *http.Request object, since gofr Request uses gorilla mux to get the path parameters, you can use `mux.SetURLVars to set the path parameters` then use that request object to create the gofr Context.

```
req := httptest.NewRequest(netHTTP.MethodPost, "/abc", nil)
req = mux.SetURLVars(req, map[string]string{"id" : "123"})

ctx := &gofr.Context {
    ....
    Request: gofrHTTP.NewRequest(req),
}
```

**Comment by PiyushSingh-ZS** [comment]
Thanks, its working
