### ISSUE TITLE
Issue while changing the redis DB

### ISSUE THREAD

**Issue by Suhas-zs** [gofr-dev/gofr#1316]
## Problem
We are unable to change the redis DB dynamically in this framework such that each and everytime, the redis instance is connected, by default it will point it to 0. That would cause a problem for other microservices to change the DB value in the redis.

## Suggested Solution
- We can have it as env based in the redis options to change the db value such that we can configure it in the env level for a service.

**Comment by coolwednesday** [comment]
@coolwednesday, please assign this issue to me.

**Comment by Suhas-zs** [comment]
- On a light of note, I have observed that, we didn't have retry mechanism implemented in background while initialising redis.  If initially the redis pinging fails, retry mechanism will help in re-initialising it.
- Can we promote this changes too, if my thought is relavant and helpful in the framework also.

cc: @Umang01-hash

**Comment by aryanmehrotra** [comment]
Redis has inbuilt support for retry, so when redis is back online it gets connected.
