### ISSUE TITLE
Pipeline Failing

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#198]
One of the example or package is failing when package and example tests are running together.
Running either of them after one passes is passed succefuly.
One Proposed solution is to make them run after one another or merge into one.

**Comment by JigarJoshi04** [comment]
I can work on this issue.
Checking if I can fix this.
Taking your proposal to separate the two.
Let me check and will keep this issue updated.
Thanks :)

**Comment by JigarJoshi04** [comment]
Hi @aryanmehrotra ,
Please assign this issue to me.
I have raised the MR.
Please review the request. 
Thanks :)

**Comment by JigarJoshi04** [comment]
Hi @aryanmehrotra ,
I am facing a broken test case issue https://github.com/JigarJoshi04/gofr/pull/2
Here if you see the workflows, I am just running the package unit test cases, nothing else
Still this is failing.

Can you please help me here?

**Comment by aryanmehrotra** [comment]
> Hi @aryanmehrotra , I am facing a broken test case issue [JigarJoshi04#2](https://github.com/JigarJoshi04/gofr/pull/2) Here if you see the workflows, I am just running the package unit test cases, nothing else Still this is failing.
> 
> Can you please help me here?

Hey - it would require to fix the tests which are panicking due to nil pointers.
