### ISSUE TITLE
Merge docs repo in this repo

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#23]
Documentation is being managed in a separate repo. So, people who want to contribute have to go to different places. Similarly, when something changes in the codebase, we need to ensure that documents are changing accordingly as part of same PR to avoid documentation conflicts. This will also help people in referring the docs directly from the codebase.

**Comment by aryanmehrotra** [comment]
It has been updated such that users can add documentation in docs directory, which will be deployed on merging PRs as follows : 

Merge to Development/main - deploy to stage : [staging.gofr.dev](https://staging.gofr.dev/docs)
Tag Release - deploy to prod : [gofr.dev](https://gofr.dev/docs)
