### ISSUE TITLE
GRPC link is not working

### ISSUE THREAD

**Issue by Adembc** [gofr-dev/gofr#338]
<img width="1384" alt="image" src="https://github.com/gofr-dev/gofr/assets/71262172/236c13f1-6bd3-42c7-bc5a-d80595ac09a3">

**Comment by aryan-mehrotra-zs** [comment]
Thanks @Adembc for reporting - we will fix this.

**Comment by vipul-rawat** [comment]
The gRPC can be accessed at https://gofr.dev/docs/advanced-guide/grpc
