### ISSUE TITLE
Documentation of connecting to different databases are not comprehensive

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#422]
As pointed on one of the posts in LinkedIn, we do not specifically have a documentation of connecting with different databases including postgres. We should have a page on "Dealing with Datasources"

**Comment by ace3** [comment]
what is the best way to setup 2 connection of same database, like mysql, etc.
since in the context, only single mysql is supported.

is there a way to inject into context ? like `c.DB2()`

i can help update the docs after knowing how to deal with multi database of same type.

**Comment by aryanmehrotra** [comment]
@ace3 it is recommended to write a new microservice If you are getting an use case to connect to two connection to a same database type.

**Comment by aryanmehrotra** [comment]
It has been updated @ https://gofr.dev/docs/advanced-guide/dealing-with-datasources
