### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#428]
<img width="592" alt="image" src="https://github.com/gofr-dev/gofr/assets/97510117/ff48834a-2888-4753-9adb-56dab97e0f9d">

here I have started my service in the default port with 8000 which is blocked ( another service is running in this port)
in that case, here I can see my service is still up. I don't know which port it is using.

**Comment by surajit-zs** [comment]
@aryan-mehrotra-zs

**Comment by vipul-rawat** [comment]
This is not necessarily a log issue, but the issue is that the program is waiting and a part of the code(subscription init) is not letting the wait get complete.

This would be tracked in #437
