### ISSUE TITLE
Unable to Build Docker Image Due to Missing File

### ISSUE THREAD

**Issue by RupeshHacker** [gofr-dev/gofr#442]
**Description:**
I'm encountering issues while trying to build a Docker image for my Go application. The Dockerfile fails during the build process, reporting errors related to missing files and compatibility with the Go version and dependencies.

**Error Messages:**
=> ERROR [stage-0 5/5] RUN go build -ldflags "-linkmode external -extldflags -static" -a examples/simple-api/main.go           2.4s

  [stage-0 5/5] RUN go build -ldflags "-linkmode external -extldflags -static" -a examples/simple-api/main.go:
2.341 go: cloud.google.com/go/pubsub@v1.37.0 requires
2.341   github.com/googleapis/gax-go/v2@v2.12.2: missing go.sum entry; to add it:
2.341   go mod download github.com/googleapis/gax-go/v2

Dockerfile:7

   5 |     COPY . .
   6 |     
   7 | >>> RUN go build -ldflags "-linkmode external -extldflags -static" -a examples/simple-api/main.go
   8 |     
   9 |     FROM alpine:latest

`ERROR: failed to solve: process "/bin/sh -c go build -ldflags \"-linkmode external -extldflags -static\" -a examples/simple-api/main.go" did not complete successfully: exit code: 1`
**Steps to Reproduce:**
1. Clone the repository containing the Dockerfile and Go application.
2. Navigate to the directory containing the Dockerfile.
3. Run `docker build . -t my-image:latest .` to build the Docker image.

**Expected Behavior:**
The Docker image should be successfully built, and the Go application should be runnable within the Docker container.

**Comment by RupeshHacker** [comment]
+ why we use **golang:1.16** instead of **golang:1.22**

**Comment by srijan-27** [comment]
Thanks @RupeshHacker for reporting this issue. We will fix this.

**Comment by RupeshHacker** [comment]
> Thanks @RupeshHacker for reporting this issue. We will fix this.

can you guid me I want to help to fix this issue
Thank you

**Comment by aryanmehrotra** [comment]
Hi @RupeshHacker can you share repository link.

**Comment by RupeshHacker** [comment]
> Hi @RupeshHacker can you share repository link as mentioned in Steps to Reproduce.

I have used main repo **https://github.com/gofr-dev/gofr**

**Comment by vipul-rawat** [comment]
@RupeshHacker for this issue the base image for docker needs to be updated from 1.16 -> 1.22, this should fix the issue as some dependencies do not support go-1.16

**Comment by RupeshHacker** [comment]
> @RupeshHacker for this issue the base image for docker needs to be updated from 1.16 -> 1.22, this should fix the issue as some dependencies do not support go-1.16

![gofroError](https://github.com/gofr-dev/gofr/assets/58428810/ba04c7da-9467-4b0d-8220-4a44985751fa)

I guess its problem of absence of `examples/simple-api/main.go` not go version problem

**Comment by vipul-rawat** [comment]
> > @RupeshHacker for this issue the base image for docker needs to be updated from 1.16 -> 1.22, this should fix the issue as some dependencies do not support go-1.16
> 
> ![gofroError](https://private-user-images.githubusercontent.com/58428810/320564112-ba04c7da-9467-4b0d-8220-4a44985751fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDYzMTIsIm5iZiI6MTcxMjc0NjAxMiwicGF0aCI6Ii81ODQyODgxMC8zMjA1NjQxMTItYmEwNGM3ZGEtOTQ2Ny00YjBkLTgyMjAtNGE0NDk4NTc1MWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEwNDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOThkYjAxODNhN2I0ZmU3MDI4NTFjZDgwM2Y0MTFmMWQxYTVmNDQ0NmEyODJiNzNlYTM4ODBlYjA3OTlkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4N-xRqkUv6fjCpyD3p9u9PIW__wD4feVfQ8946vs70E)
> 
> I guess its problem of absence of `examples/simple-api/main.go` not go version problem

The absence was due to an incorrect path, but the go version would have also caused errors as we support 3 latest versions of go, and so the dependencies would break the program for go 1.16
