### ISSUE TITLE
Add missing config for Tracer in Observability documentation

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#458]
Following config is missing in https://gofr.dev/docs/quick-start/observability
```
TRACE_EXPORTER=zipkin
```
<img width="948" alt="image" src="https://github.com/gofr-dev/gofr/assets/44036979/6ed1d422-3ed0-4f74-a0df-e4edda63d0f8">

**Comment by SuyeshBadge** [comment]
Hey @aryanmehrotra Could you please assign this to me.

**Comment by srijan-27** [comment]
@aryanmehrotra - This is fixed now. Closing the issue.
