### ISSUE TITLE
Improve details in debug log for Migrations

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#477]
Currently, when we run migrations, we only see the queries which are being executed, add more debug logs to make it more informative.

For example: When we check if gofr_migrations table exist or not we should also print the response received from the database.

**Comment by tdadadavid** [comment]
@aryanmehrotra can I be assigned to this

**Comment by aryanmehrotra** [comment]
Sure @tdadadavid will assign to you.

**Comment by aryanmehrotra** [comment]
@tdadadavid wanted to check if you are working on this issue?

**Comment by tdadadavid** [comment]
My apologies, I have been unavailable.
I will not be able to handle this now.
Thanks

**Comment by kailashchoudhary11** [comment]
Hey @aryanmehrotra, I would like to take on this issue.

**Comment by aryanmehrotra** [comment]
Sure @kailashchoudhary11 Assigning it to you!

**Comment by srijan-27** [comment]
@kailashchoudhary11 - Are you are still working on this? If yes, let me know if you have any queries.

**Comment by kailashchoudhary11** [comment]
Hey @srijan-27 I'm a bit busy due to end sem exams. Will start working on it during weekends.

**Comment by srijan-27** [comment]
Sure @kailashchoudhary11, just wanted to check.

**Comment by kailashchoudhary11** [comment]
Hey @srijan-27, I had some queries and have texted you on discord.

**Comment by srijan-27** [comment]
Sure @kailashchoudhary11, let's discuss regarding this.

**Comment by kailashchoudhary11** [comment]
> Sure @kailashchoudhary11, let's discuss regarding this.

I have sent you a personal message on discord @srijan-27
