### ISSUE TITLE
Fix logs for PubSub datasources

### ISSUE THREAD

**Issue by vipul-rawat** [gofr-dev/gofr#484]
- [x] Add proper context for logs
- [x] Log the pubsub messages that are recieved
- [x] Fix log order for MQTT and display topic subscribed to

Issue extends #472

**Comment by royalrajputayush** [comment]
I want to work on this issue, please assign me this under gssoc level 3

**Comment by srijan-27** [comment]
@royalrajputayush - This issue was already done as part of mentioned PR.
You can check out the parent issue (474), and work on that.
