### ISSUE TITLE
clickhouse database support

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#494]
Implement clickhouse DB based on the following [documentation](https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/README.md).

**Comment by TheMarvelFan** [comment]
Hi,
Is anyone working on this issue?

**Comment by aryanmehrotra** [comment]
No, you want to work on this? It is the next database we want, so we would need active participation and close it ASAP.

**Comment by TheMarvelFan** [comment]
Yes I would like to take up this issue.
I would appreciate it if you can assign it to me under the GSSOC '24 label.
Thanks.

**Comment by aryanmehrotra** [comment]
We are not part of GSSOC '24

**Comment by TheMarvelFan** [comment]
I saw your project listed on their Project board, that's why I assumed you were. 
Nonetheless, I still want to work on this issue.

**Comment by aryanmehrotra** [comment]
Sure, assigning it to you. 
Please refer cassandra and mongoDB.
Share the interface once done so it can be reveiwed first before going to the actual implementation

**Comment by aryanmehrotra** [comment]
@TheMarvelFan are you working on this?

**Comment by TheMarvelFan** [comment]
Yes I am working on this. I need a bit more time as I am also busy with my semester exams at the moment. Will be opening a PR today or tomorrow.

**Comment by TheMarvelFan** [comment]
Hi,

I apologize for taking so long, but I won't be able to find the time to work on this issue for the next 2 weeks or so. But, I understand the urgency of this issue, and am unassigning myself so someone else can complete it in time. 

Thanks
