### ISSUE TITLE
badgerDB support for key value

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#499]

**Comment by vishaljangid1729** [comment]
Hey @vikash 

I've got quite a bit of experience with badgerDB, having used it extensively in various projects.

Could you provide more details about the specific requirements or use cases for this feature? I'd love to dive deeper into it and see how I can contribute to its implementation.

Looking forward to hearing from you!

**Comment by aryan-mehrotra-zs** [comment]
Hi @vishaljangid1729 we would want it to be implemented in the similar way Mongo is being implemented.
we have defined it interface and methods in gofr : https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/mongo.go
and its implementation exists in a different repo : https://github.com/vipul-rawat/gofr-mongo

**Comment by aryanmehrotra** [comment]
Hi @vishaljangid1729 we would want it to be implemented in the similar way Mongo is being implemented.
we have defined it interface and methods in gofr : https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/mongo.go
and its implementation exists in a different repo : https://github.com/vipul-rawat/gofr-mongo

Moreover, you can join discord server where we can connect as well to discuss more on this : https://discord.gg/Kb3cnx9r
