### ISSUE TITLE
Support for serving static files

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#502]

**Comment by vipul-rawat** [comment]
#528

**Comment by interrrp** [comment]
How should the API look like? I'm thinking of something like this:

```go
app.AddStaticFiles("/static", "./static")
```

**Comment by vikash** [comment]
We can follow a convention also. If a public folder is present, files in that folder can be accessed by the server.

**Comment by KedarisettiSreeVamsi** [comment]
Can I try to work on this?
