### ISSUE TITLE
Framework should make dealing with S3 files easier

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#503]
We can have an implementation where s3 files can be treated like a local filesystem.

**Comment by kurayami07734** [comment]
I would like to work on this
do you have some references?

**Comment by aryanmehrotra** [comment]
Hey, you can implement this the way file store has been implemented.

**Comment by noxymon** [comment]
hi @aryanmehrotra , 
i would like to contribute on this issue, 

could you assign to me ?

**Comment by coolwednesday** [comment]
@aryanmehrotra Please assign this issue to me.

**Comment by srijan-27** [comment]
@coolwednesday - Assigned this to you!

**Comment by ManuelReschke** [comment]
@coolwednesday , looks like you make good progress? Whats the status?

**Comment by coolwednesday** [comment]
> @coolwednesday , looks like you make good progress? Whats the status?

@ManuelReschke We will be able to support file as well as filesystem operations for a single s3 bucket that is general purpose and files stored are unversioned, if my PR merges.
