### ISSUE TITLE
Support FTP/SFTP files abstraction

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#505]

**Comment by Sarthak027** [comment]
Hi @vikash I want to work on this. Can u please explain this issue to me??

**Comment by aryanmehrotra** [comment]
Hi @Sarthak027 we will be merging the interface which will has to be implemented for SFTP and FTP similar to how we are supporting mongoDB.

**Comment by coolwednesday** [comment]
Hi @aryanmehrotra . Please Assign this issue to me.
