### ISSUE TITLE
Add websocket support

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#507]

**Comment by SUKANT007** [comment]
@aryan-mehrotra-zs / @vipul-rawat  I would like to work on this issue.

**Comment by aryanmehrotra** [comment]
> @aryan-mehrotra-zs / @vipul-rawat  I would like to work on this issue. Can you please assign it to me.

Sure, assigning to you!

Please discuss first on how user will be using this feature.

**Comment by Umang01-hash** [comment]
@SUKANT007 just wanted to re-check you want to pick up this issue and work on it.... ?

**Comment by SUKANT007** [comment]
Yes @Umang01-hash, I would like to pick up, We can have discussion on it how we want users to use this. If you could share the details that would be helpful. 

Mainly we need to implement webSocket Upgrader and provide webSocket connection to the user. I'm thinking of using 
https://github.com/gorilla/websocket to implement that.

Also I was thinking of giving them the option to get WebSocket connection from context, Please share your thoughts on it or are we thinking of exposing that in some other way.

**Comment by Umang01-hash** [comment]
Sure @SUKANT007 I agree with your thoughts of implementing the webSocket Upgrader and provide connection to user.

Regarding `option to get WebSocket connection from context` ,it is not a bad idea but also we need to think of different use-cases which can ease out the process to check for open socket connection.
