### ISSUE TITLE
Support auto retry for databases in case of connection breakdown

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#510]
- [ ] SQL - https://github.com/gofr-dev/gofr/pull/530
- [ ] REDIS

**Comment by aryan-mehrotra-zs** [comment]
Closing this issue as, if connection to SQL fails in between, by default it creates a connection once SQL or REDIS is available.

**Comment by aryanmehrotra** [comment]
Closing this issue as, if connection to SQL fails in between, by default it creates a connection once SQL or REDIS is available.
