### ISSUE TITLE
Support connection pool configurations in database

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#511]

**Comment by TheMarvelFan** [comment]
Hi,
Can you provide more context on this issue?
Thanks

**Comment by aryanmehrotra** [comment]
Right now setting such as number of idle connections, max connection and other db connections are not configurable we want to support that but not from configs.

**Comment by TheMarvelFan** [comment]
I see many approaches you can take to implement this, such as Providing an API endpoint that allows administrators to update the connection pool settings at runtime, employing a database table to store these settings, which the application reads and applies at startup or during runtime, etc.

How do you suggest to approach this issue? (please do reply if you had something specific in mind)

**Comment by srijan-27** [comment]
Done in #739
