### ISSUE TITLE
Fix SQL logs in case of errors

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#519]
Currently, when error occurs mysql logs are coming in the following way. 
Rather, it should be structured similar to other logs.

<img width="1033" alt="image" src="https://github.com/gofr-dev/gofr/assets/44036979/f0079f21-22d2-4cde-b947-0fc73bf436da">

This screenshot is captured by running the example `http-server` and disconnecting the database after application startup.

**Comment by srijan-27** [comment]
This log is coming from the [sql-driver](github.com/go-sql-driver/mysql) which is being used. Reference [ticket](https://github.com/go-sql-driver/mysql/issues/1120).
The implementation of [mysql.Logger](https://pkg.go.dev/github.com/go-sql-driver/mysql@v1.8.1#Logger) interface is not feasible on our side, so format for this log is not updatable.
