### ISSUE TITLE
Enhance metrics

### ISSUE THREAD

**Issue by srijan-27** [gofr-dev/gofr#529]
- A new counter metric needs to be added which represents server errors (`app_server_error`)
- A new counter metric for circuit open counts (`app_circuit_open_count`)
- Add hostname and database labels in `app_sql_stats` and `app_mongo_stats` metrics
- Add hostname in `app_redis_stats` metric
- Add consumer_group label in pubsub metrics

**Comment by illenko** [comment]
I may take it.

**Comment by srijan-27** [comment]
@illenko - Sure, assigning this to you.
