### ISSUE TITLE
Add support to connect to postgres with AddRESTHandlers.

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#535]
Issue described here as potential Issue 4: https://medium.com/@kostiantynillienko/gofr-features-and-potential-improvements-review-configuration-http-server-client-redis-e4da36819b22

> After inspecting the source code I have found the reason in /pkg/gofr/crud_handlers.go , ? used as a placeholder, but PostgreSQL requires an ordered one like $1:

**Comment by illenko** [comment]
I will try to fix it.
