### ISSUE TITLE
Create an Error package and have some pre-defined errors

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#541]
For example: 
GofrError, DBError, PubSubError etc.

pkg/errors  package has Wrap and WithStack which can be used to provide more contexts.

**Comment by MadhushaPrasad** [comment]
Can you assign this issue to me? @vikash

**Comment by Umang01-hash** [comment]
Sure @MadhushaPrasad assigning the issue to you. Please discuss how the user's will be using these errors (just the raw approach ) before submitting the PR.

**Comment by MadhushaPrasad** [comment]
> Wrap and WithStack

can you give me some details about this Wrap and WithStack? @vikash

**Comment by Umang01-hash** [comment]
> > Wrap and WithStack
> 
> can you give me some more details about this Wrap and WithStack? @vikash

@MadhushaPrasad you can refer here : https://github.com/pkg/errors?tab=readme-ov-file#adding-context-to-an-error
To see what is  `errors.Wrap`.

I also found this repository for go-errors: https://github.com/go-errors/errors

**Comment by MadhushaPrasad** [comment]
> > > Wrap and WithStack
> > 
> > 
> > can you give me some more details about this Wrap and WithStack? @vikash
> 
> @MadhushaPrasad you can refer here : https://github.com/pkg/errors?tab=readme-ov-file#adding-context-to-an-error To see what is `errors.Wrap`.
> 
> I also found this repository for go-errors: https://github.com/go-errors/errors

ok thank you

**Comment by Umang01-hash** [comment]
@MadhushaPrasad Hey!
Did we came to any raw implementation on how the users will be using our errors package?
