### ISSUE TITLE
Implement Observability features for MongoDB

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#570]
Currently, MongoDB is supported but observability features are not added.

**Comment by illenko** [comment]
We have to update this repository code https://github.com/vipul-rawat/gofr-mongo, or create wrappers in gofr core?

**Comment by vipul-rawat** [comment]
@illenko we are moving the [gofr-mongo](https://github.com/vipul-rawat/gofr-mongo) repo to the gofr-dev organization, will be updating in the same, will add tickets there too!

**Comment by srijan-27** [comment]
Done with #616
