### ISSUE TITLE
MongoDB does not work

### ISSUE THREAD

**Issue by AchimGrolimund** [gofr-dev/gofr#574]
https://github.com/gofr-dev/gofr/blob/dddf1473be2c0bf682837e9fed8ed5bd80a06cec/docs/advanced-guide/injecting-databases-drivers/page.md?plain=1#L61

Here i got an Error:
```
Cannot use app.Metrics() (type metrics.Manager) as the type Metrics Type does not implement Metrics as some methods are missing: SetGauge(name string, value float64)
```
![image](https://github.com/gofr-dev/gofr/assets/22026079/c7c3c0c3-9114-48e6-9599-d0d5cecbddc3)

Here is my full Code:
```go
package main

import (
	mongo "github.com/vipul-rawat/gofr-mongo"
	"go.mongodb.org/mongo-driver/bson"

	"gofr.dev/pkg/gofr"
)

type Report struct {
	DocumentUri        string `bson:"documenturi" json:"documenturi"`
	Referrer           string `bson:"referrer" json:"referrer"`
	ViolatedDirective  string `bson:"violateddirective" json:"violateddirective"`
	EffectiveDirective string `bson:"effectivedirective" json:"effectivedirective"`
	OriginalPolicy     string `bson:"originalpolicy" json:"originalpolicy"`
	Disposition        string `bson:"disposition" json:"disposition"`
	BlockedUri         string `bson:"blockeduri" json:"blockeduri"`
	LineNumber         int    `bson:"linenumber" json:"linenumber"`
	SourceFile         string `bson:"sourcefile" json:"sourcefile"`
	StatusCode         int    `bson:"statuscode" json:"statuscode"`
	ScriptSample       string `bson:"scriptsample" json:"scriptsample"`
}

func main() {
	app := gofr.New()

	// using the mongo driver from `vipul-rawat/gofr-mongo`
	db := mongo.New(app.Config, app.Logger(), app.Metrics())

	// inject the mongo into gofr to use mongoDB across the application
	// using gofr context
	app.UseMongo(db)

	//app.POST("/mongo", Insert)
	app.GET("/report", Get)

	app.Run()
}

func Get(ctx *gofr.Context) (interface{}, error) {
	var result Report

	err := ctx.Mongo.Find(ctx, "reports", bson.D{{}} /* valid filter */, &result)
	if err != nil {
		return nil, err
	}

	return result, nil
}

```

**Comment by vipul-rawat** [comment]
@AchimGrolimund The issue has been fixed, moreover we are planning to move the datasource repo to the gofr-dev organisation itself https://github.com/gofr-dev/datasource-mongodb.
Issue was that the app.Metrics() interface changed in gofr core so there was a mismatch in the interfaces.

**Comment by AchimGrolimund** [comment]
I wil test that out this evening.
But then there is another issue in the Doku 😉

**Comment by AchimGrolimund** [comment]
@vipul-rawat 
The call now fits, but there is an issue in the mod.

```
$ go run main.go 
# gofr.dev/pkg/gofr/metrics
..\..\..\..\go\pkg\mod\gofr.dev@v1.5.0\pkg\gofr\metrics\register.go:27:7: invalid receiver type Manager (pointer or interface type)
```

**Comment by vipul-rawat** [comment]
@AchimGrolimund can you please share the go.mod file you are using for the testing.

**Comment by AchimGrolimund** [comment]
@vipul-rawat 
Here are the Test Repo:
https://github.com/AchimGrolimund/CSP-Scout-API

**Comment by vipul-rawat** [comment]
@AchimGrolimund I am unable to produce the same error that you mentioned! It seems to be working just fine
![image](https://github.com/gofr-dev/gofr/assets/44166352/0ffc5d66-fd60-45d0-8e14-b0494275e2bc)
You can try doing `go mod tidy` or clean modcache using `go clean -modcache` and then downloading the mod packages using `go mod tidy`

**Comment by AchimGrolimund** [comment]
> @AchimGrolimund I am unable to produce the same error that you mentioned! It seems to be working just fine ![image](https://private-user-images.githubusercontent.com/44166352/329013046-0ffc5d66-fd60-45d0-8e14-b0494275e2bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTc3NDksIm5iZiI6MTcxNTE5NzQ0OSwicGF0aCI6Ii80NDE2NjM1Mi8zMjkwMTMwNDYtMGZmYzVkNjYtZmQ2MC00NWQwLThlMTQtYjA0OTQyNzVlMmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE5NDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZWZkNTBkNTY5OTAyYmE3NjgwMGYxYjgyZGI4Y2EyMmYwOWNkOWU1YWE3YTU4YmViMTBlYTU2OTYwY2UwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gmNeUzaux9M_YVADCgBQWszkhVbNAGnLEJy-C7f0LvY) You can try doing `go mod tidy` or clean modcache using `go clean -modcache` and then downloading the mod packages using `go mod tidy`

yes this is what i allways doo. i run `go get -u ./...` tu upgrade all mods packages then `go mod tidy`.. hmm i wil try out the `go clean -modcache`

**Comment by AchimGrolimund** [comment]
🥳  `go clean -modcache` solved my problem. I never had to do this before, so this was also unknown to me. I always assumed that I could update everything with `go get -u ./...` and download the mods again with `go mod tidy` using the `go.mod/.sum` file.

Thanks for testing and solving the problem!
