### ISSUE TITLE
NATS support 

### ISSUE THREAD

**Issue by linux-china** [gofr-dev/gofr#584]
[NATS](https://nats.io/) is more than PubSub with lots features: 

* Pub/Sub
* Streaming
* Key-Value
* Object Store
* Service Framework:  https://natsbyexample.com/examples/services/intro/go

**Comment by gedw99** [comment]
Would be really awesome to see nats supported. 

Descant then eithe embed nats Jetstream , use an external NATS Jetstream or using the Syndia Cloud running NATS Jetstream in which AWS or GCP or Azure.

I tend to use Embedded for testing, and my own NATS super cluster for Production.

—-

I am using this NAT HTTP gateway to give me an S3 system , without S3. Is uses the NATS object store and scales out multi region is your using a NATS Super Cluster.

https://github.com/wpnpeiris/nats-gateway

**Comment by gedw99** [comment]
Also there are examples with videos here for the many aspects of NATS

https://github.com/synadia-io/rethink_connectivity

You can send logs, traces and metrics to NATS Jetstream. This is async and can reduce the amount of sub systems you need for your telemetry as well as unifying all that data from your many mi Roderick into a global view inside nats.

**Comment by mfreeman451** [comment]
I need this for a project of mine and will be submitting a PR shortly.

**Comment by srijan-27** [comment]
@mfreeman451 - Sure, assigning this to you then.
