### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by Princegupta101** [gofr-dev/gofr#590]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by aryanmehrotra** [comment]
It is already present https://github.com/gofr-dev/gofr?tab=coc-ov-file
