### ISSUE TITLE
Create a new release v1.0.0 and give credit to all past contributors in its notes

### ISSUE THREAD

**Issue by vikash** [gofr-dev/gofr#6]

**Comment by aryan-mehrotra-zs** [comment]
# v1.0.0

Dear GoFr Community,

We're thrilled to announce that GoFr is now an open-source project, marking a new chapter in its evolution. We extend our heartfelt gratitude to all past and present contributors who've been instrumental in GoFr's development.

As part of our security measures, we've removed the complete project history, ensuring its integrity moving forward.
 
By making GoFr open source, we aim to foster a collaborative environment for developers of all backgrounds to innovate and enhance the project.

We invite you to explore the newly open-sourced GoFr, fork it, and contribute to its development. Your expertise is invaluable, and we look forward to new ideas and collaborative efforts.

Feel free to reach out with questions, feedback, or suggestions. Thank you for your contributions and support. 

Let's shape GoFr's next chapter together!

## Release Notes
### Features

- REST, gRPC server, Cron, and CMD creation
- Support for SQL and NoSQL Data Stores with Auto-Initialization
  - **SQL**: MySQL, MS SQL, PostgreSQL
  - **NoSQL**: MongoDB, DynamoDB, Cassandra, Yugabyte, Redis
  - **Pub/Sub**: Kafka (with Avro), Azure Event Hubs, AWS EventBridge, Google Pub/Sub
  - **Search Engines**: Apache Solr, Elastic Search
- Support for file stores with remote file abstraction
  - **Remote File Stores**: FTP, SFTP, AWS S3, GCP, Azure
- Support for AWS SNS Notifier
- Predefined logs with log levels for STDOUT and JSON
- Database state management using Migrations
- Inbuilt middleware for OAuth, Performance Monitoring (NewRelic), CORS, Tracing (Zipkin and GCP)
- Support for runtime configuration overrides
- Observability through traces, metrics, health checks, and heartbeats


## Past Contributors:
1. Vikash Kumar ([vikash](https://github.com/vikash))
2. Stella Rani ([stella551](https://github.com/stella551))
3. Aryan Mehrotra ([mehrotra234](https://github.com/mehrotra234))
4. Umang Mundhra ([umang01-hash](https://github.com/umang01-hash))
5. Vipul Rawat ([vipul-rawat](https://github.com/vipul-rawat))
6. Akshat Kumar Singhal ([akshat-zopsmart](https://github.com/akshat-zopsmart))
7. Abishek R V ([abishek-r-v]([https://github.com/abishek-r-v]))
8. Atul Gond ([atulkumargond]([https://github.com/atulkumargond]))
9. Mahak Singhania ([mahaksinghania-zs](https://github.com/mahaksinghania-zs))
10. Gurpreet Kumar ([Gurpreet-zs](https://github.com/Gurpreet-zs))
11. Tejaswi Sapala ([Tejaswi-zs]([https://github.com/Tejaswi-zs](https://github.com/Tejaswi-zs)))
12. Shubham Sirothiya ([shubham-zs]([https://github.com/shubham-zs](https://github.com/shubham-zs)))
13. Shashank Shekhar ([ssshekhu53]([https://github.com/ssshekhu53](https://github.com/ssshekhu53)))
14. Vatturi Naga Surya Prakash ([suryap-zs]([https://github.com/suryap-zs](https://github.com/suryap-zs)))
15. Subrahmanyam ([subrahmanyam470]([https://github.com/subrahmanyam470](https://github.com/subrahmanyam470)))
