### ISSUE TITLE
Addition for a Code Playground

### ISSUE THREAD

**Issue by hollermay** [gofr-dev/gofr#605]
I believe it should have a playground to code same we have coding playground at websites to test tools or any programming language and if we add some basic code to execute will also be a good way to create engagement with suggestion codes below the playground or at a sidebar.

**Comment by aryanmehrotra** [comment]
@hollermay This seems to be a nice feature, but users can also use Go Playground.
We can continue this discussion in the website repo where it will be suitable! 
I have created the following ticket: https://github.com/gofr-dev/website/issues/54
