### ISSUE TITLE
Support Migrations for Mongo DB

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#620]
Add support for Migration for external DB.

We support mongoDB as an external DB, migrations should also be supported for the same.

**Comment by TheMarvelFan** [comment]
Hi,
What's the latest on this issue?

**Comment by aryanmehrotra** [comment]
Support is yet to be added for the same @TheMarvelFan

**Comment by coolwednesday** [comment]
@vipul-rawat please assign this to me.
