### ISSUE TITLE
Support for binding multipart request form data

### ISSUE THREAD

**Issue by nulldiego** [gofr-dev/gofr#623]
Hi, I am trying to bind a multipart request that has a file and some form values. The file binds perfectly but it's missing the rest of the form data.

```
type Dataset struct {
	Id      int                   `json:"id"`
	Name    string                `json:"name"`
	Authors string                `json:"authors"`
	File    *multipart.FileHeader `file:"file" json:"-"`
}
```

```
if err := ctx.Bind(&dataset); err != nil {
	ctx.Logger.Errorf("error binding: %v", err)
	return nil, errors.New("invalid body")
}
```

This is the request:
```
curl --location 'http://localhost:8000/datasets' \
--header 'X-API-Key: {{token}}' \
--form 'name="test name"' \
--form 'authors="test authors"' \
--form 'file=@"/home/dev/test-data/dataset.csv"'
```

Only the file gets bound, the other fields are empty. Am I doing something wrong? I can see that the http request has the form fields informed at `MultipartForm.Value` but I can't access that through `gofr.Context` to bind them manually.

Thank you!

**Comment by srijan-27** [comment]
@nulldiego - Thanks for reporting this. It is not yet supported in the framework.
Will keep this ticket in track with the same.

**Comment by vipul-rawat** [comment]
@nulldiego we are working on supporting bind for other form data as well, but will be doing that on `form` tag or no tag but exported field when incoming content/type is `application/form-data`
