### ISSUE TITLE
There is no hover effect for the social media icons in the footer

### ISSUE THREAD

**Issue by Shelbybosss** [gofr-dev/gofr#633]
I will add good hover effect to the icons which will improve UI.
![footer](https://github.com/gofr-dev/gofr/assets/102911609/b4189f1e-02f2-49ca-bddc-7e730e55926c)

Assign me this issue

**Comment by Shelbybosss** [comment]
@vikash Assign me this issue

**Comment by aryanmehrotra** [comment]
Hi @Shelbybosss I will created the issue in the website repo wher you can contribute on the same!

https://github.com/gofr-dev/website/issues/58
Thanks
