### ISSUE TITLE
Enhance Readme 

### ISSUE THREAD

**Issue by aasthakourav20** [gofr-dev/gofr#636]
What's missing in this repository !!
The README file is the first thing users and contributors see when they visit your repository. It serves several key purposes:

Introduction and Overview: It provides a clear and concise introduction to your project, explaining what it does, its purpose, and why it’s valuable.
Installation Instructions: It guides users on how to set up and install the project on their local machines, ensuring they can quickly get started.
Usage Guidelines: It offers detailed instructions on how to use the project, including examples and common use cases.
Contribution Information: It informs potential contributors on how they can contribute to the project, including any guidelines or requirements they should follow.
License Information: It specifies the licensing terms under which the project is distributed, ensuring users and contributors understand their rights and obligations.

Kindly assign this issue to me under GSSoC'24

**Comment by aryanmehrotra** [comment]
Hey, these changes are already present, and usage docs are present @ https://gofr.dev/docs
