### ISSUE TITLE
Redis lock

### ISSUE THREAD

**Issue by illenko** [gofr-dev/gofr#637]
## Problem:
Now we have [go-redis](http://github.com/redis/go-redis/v9) and for implementing distributed lock (common case for Redis usage) users have to write custom implementations of Locks.

## Proposal:
To simplify the locks aquiring / releasing process would be better to have [redislock](https://github.com/bsm/redislock) out of the box.

## In the code usage may look like:
```go
lock, err := ctx.Redis().Locker().Obtain(ctx, "my-key", 100*time.Millisecond, nil)
```

**Comment by yigithankarabulut** [comment]
Hi, I started to try something to implement redislock to gofr properly. Could you assign to me.

**Comment by illenko** [comment]
Hi @yigithankarabulut , is there any update?

**Comment by aryanmehrotra** [comment]
As there is no update un-assigning the ticket.

**Comment by Umang01-hash** [comment]
@illenko I think we can use distributed lock with the existing client in GoFr by referring to this documentation: https://redis.io/glossary/redis-lock/

If it satisfies your use-case feel free to close the issue, if not please tell us more about your use-case. Will be happy assisting you
