### ISSUE TITLE
Options to set table name and API path for REST handlers.

### ISSUE THREAD

**Issue by illenko** [gofr-dev/gofr#647]
## Problem

Now in REST Handlers GoFr uses lowercased struct name for API path and snake-cased struct name for DB table. It causes potential problems with table naming and following REST API best practices.
Source code (`crud_handlers.go`):
```go

func scanEntity(object interface{}) (*entity, error) {
        ...
	structName := entityType.Name()
        ...
	return &entity{
		name:       structName,
		entityType: entityType,
		primaryKey: primaryKeyFieldName,
	}, nil
}

func (a *App) registerCRUDHandlers(e entity, object interface{}) {
	if fn, ok := object.(Create); ok {
		a.POST(fmt.Sprintf("/%s", e.name), fn.Create)
	} 
        ...
}

func (e *entity) Create(c *Context) (interface{}, error) {
	...
	stmt := sql.InsertQuery(c.SQL.Dialect(), toSnakeCase(e.name), fieldNames)
        ...
}
```

## Proposal

Allow to set custom values for:
* DB table name
* REST API path

## Expected usage:
```go
type User struct {
	Id         int    `json:"id"`
	Name       string `json:"name"`
	Age        int    `json:"age"`
	IsEmployed bool   `json:"isEmployed"`
}

func (m *User) TableName() string {
    return "user"
}

func (m *User) RestPath() string {
    return "users"
}
```

**Comment by illenko** [comment]
@aryanmehrotra , if you ok with this, I can take it.

**Comment by aryanmehrotra** [comment]
Sure @illenko We also need to think about the expected usage, such that implementing these two remains optional.

Also what if we add variadic parameter to AddRESTHandler method where we take these.

**Comment by reski-rukmantiyo** [comment]
hi all, I think this is a good idea to overcome the limitation of GoFr right now.
