### ISSUE TITLE
middlewares: cannot overwrite the predefined middleware set

### ISSUE THREAD

**Issue by davewhit3** [gofr-dev/gofr#652]
**Describe the bug**
When I try change cors behavior then i can't do it, because we have pre defined middlewares set

1. The code is

```go
// NewRouter creates a new Router instance.
func NewRouter(c *container.Container) *Router {
	muxRouter := mux.NewRouter().StrictSlash(false)
	muxRouter.Use(
		middleware.Tracer,
		middleware.Logging(c.Logger),
		middleware.CORS(),
		middleware.Metrics(c.Metrics()),
	)

	return &Router{
		Router: *muxRouter,
	}
}
```

2. The error is in the cors middleware

```go
func CORS() func(inner http.Handler) http.Handler {
	return func(inner http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Access-Control-Allow-Origin", "*")
			w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE, PATCH")

			if r.Method == http.MethodOptions {
				w.WriteHeader(http.StatusOK)
				return
			}

			w.Header().Set("Access-Control-Allow-Headers", "content-type")

			inner.ServeHTTP(w, r)
		})
	}
}
```
Now we can't override headers behavior because it's always executed before any other middleware.
When I call the OPTIONS method, the execution of this middleware is interrupted.

```go
	if r.Method == http.MethodOptions {
		w.WriteHeader(http.StatusOK)
		return
	}
```

```
HTTP/1.1 200 OK
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE, PATCH
Access-Control-Allow-Origin: *
X-Correlation-Id: e88db3054487af8ea70183f8eebe46ed
Date: Mon, 27 May 2024 11:06:07 GMT
Content-Length: 0
```

**Expected behavior**
CORS middleware should not interrupt middleware execution. 
We can add the method to the overriding set of predefined middleware.

**Environments (please complete the following information):**
- OS: Linux,Mac,Windows
- gofr version  v1.6.1
- go version 1.22

**Comment by Umang01-hash** [comment]
@davewhit3 thankyou for reporting the issue. Regarding overriding the pred-defined middlewares, GoFr don't support it as of now, we want our users to use the pre-defined middlewares for common use cases like auth, CORS etc.

But if you could tell us your use-case and the problems you are facing maybe we can help you. We can support setting CORS specific headers in the middleware through configs.

**Comment by davewhit3** [comment]
@Umang01-hash thanks for your reply.

I need to set the `Access-Control-Allow-Headers` header for the HTTP Options method.
Now I have a CORS error from the react app:
```
Access to fetch at 'http://127.0.0.1:8000/auth/login' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by Umang01-hash** [comment]
@davewhit3 Thankyou for telling the use-case scenario.

To help you we will make the CORS header configurable and allow user to set custom header through configs.
I think this way you can set your desired headers in the request.

**Comment by vikash** [comment]
@Umang01-hash - Instead of making it configurable, we should be able to infer based on all the routes which are added. Also, content-type should be allowed.
