### ISSUE TITLE
Auth Middleware Not working as expected 

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#664]
- in our app, we are using auth like this but it is giving an unstoppable 500 and not giving any error message also.

``` go
	app.EnableOAuth(app.Config.Get("localhost:8002/jwks?realmID=633af011-2503-4abc-93ba-fef6f032c414"), 3000)
```

<img width="1383" alt="Screenshot 2024-05-28 at 3 45 12 PM" src="https://github.com/gofr-dev/gofr/assets/97510117/d987f2a1-abe5-4f9d-a09c-08c116d02dad">

ref: https://github.com/gofr-dev/gofr/blob/89994c7774fd3c267d82441eaf5293dc57eb2d4f/pkg/gofr/http/middleware/oauth.go#L61

**Comment by surajit-zs** [comment]
and I did not see any metrics for this call. I think we should add that as well.

**Comment by aryanmehrotra** [comment]
Metrics we will add as part of a different ticket.
