### ISSUE TITLE
Fix Metrics missing for HTTPService

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#666]
**Describe the bug**
If service A hits `http://google.comma` which does not exist we would get a 500 Error, for which metrics should be pushed, but it is not happening.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   a.EnableOAuth("http://google.comma", 10)
   
   Add the following in any example's main.go
   ```

2. The error is

   ```
   Metrics are missing @ localhost:2121/metrics
   ```

**Expected behavior**
Even though the request failed metrics should come for the same.

**More description**
It is happening because it is being checked if resp is not nil @ https://github.com/gofr-dev/gofr/blob/89994c7774fd3c267d82441eaf5293dc57eb2d4f/pkg/gofr/service/new.go#L173

**Comment by sipsdaoracle** [comment]
Hi @aryanmehrotra and @srijan-27 would you please assign this to me if no one is looking at it.

**Comment by srijan-27** [comment]
@sipsdaoracle - Sure, assigning this to you.

**Comment by srijan-27** [comment]
Hi @sipsdaoracle - just wanted to know if you are working on this? If any issues, do let me know.
