### ISSUE TITLE
Fix Health-Check Response when no external service is attached

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#672]
**Describe the bug**
`/.well-known/health` returns an empty response, when no db or external service is connected.

**To Reproduce**

Create service without any database or external service.

**Expected behavior**
It should return the status of service as `UP`.

**More description**
In, case if any of the dependent service is down the status should be degraded

**Comment by TheMarvelFan** [comment]
Hi,

Is anyone working on this issue?

**Comment by aryanmehrotra** [comment]
No, not yet

**Comment by TheMarvelFan** [comment]
Yes I want to work on this issue.
I would appreciate it if you can assign it to me under the GSSOC '24 label.
Thanks.

**Comment by srijan-27** [comment]
@TheMarvelFan - We are not part of GSSOC'24.
