### ISSUE TITLE
Support for retry of failed dowstream http request

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#709]
Currently, if a downstream http request fails response is returned without any retry.

We should give an option to user to add retry count for a downstream request.

**Comment by kailashchoudhary11** [comment]
hey @aryanmehrotra I would like to work on this

**Comment by srijan-27** [comment]
@kailashchoudhary11 - Sure, assigning this to you!

**Comment by kailashchoudhary11** [comment]
Hey, should we give an option to add retry count for all of the downstream requests? GET, PUT, POST, PATCH, DELETE?

**Comment by Umang01-hash** [comment]
> Hey, should we give an option to add retry count for all of the downstream requests? GET, PUT, POST, PATCH, DELETE?

Yes @kailashchoudhary11 giving that option could be helpful for users.

**Comment by srijan-27** [comment]
@kailashchoudhary11 - are you working on this?

**Comment by kailashchoudhary11** [comment]
@srijan-27 yes I'm working on it.
