### ISSUE TITLE
Switch ti 1.9.0 `cannot use redisMock (variable of type *MockRedis)`

### ISSUE THREAD

**Issue by AchimGrolimund** [gofr-dev/gofr#712]
**Describe the bug**
```
$ go run cmd/csp-scout-api/main.go 
# gofr.dev/pkg/gofr/container
..\..\..\..\go\pkg\mod\gofr.dev@v1.9.0\pkg\gofr\container\mock_container.go:27:20: cannot use redisMock (variable of type *MockRedis) as Redis value in assignment: *MockRedis does not implement Redis (missing method BitFieldRO) 

```

**To Reproduce**
Clone my Repository: https://github.com/AchimGrolimund/CSP-Scout-API
try to run it: `go run cmd/csp-scout-api/main.go`

1. The code is

   ```go
   
   ```

2. The error is

```
   # gofr.dev/pkg/gofr/container
..\..\..\..\go\pkg\mod\gofr.dev@v1.9.0\pkg\gofr\container\mock_container.go:27:20: cannot use redisMock (variable of type *MockRedis) as Redis value in assignment: *MockRedis does not implement Redis (missing method BitFieldRO)
```

**Expected behavior**
starting and running Webserver

**Screenshots**

**Environments (please complete the following information):**
go version go1.22.4 windows/amd64

**More description**

**Comment by AchimGrolimund** [comment]
hmm i test it out on all the latest releases until 1.4.0 and i got this message, this is a bit weird. and also i do not use redis or something like that.

**Comment by aryanmehrotra** [comment]
Hi @AchimGrolimund running it is working fine on Mac silicon M2. Can you please check it once on the latest version of gofr?

**Comment by AchimGrolimund** [comment]
Hey @aryanmehrotra thank you so much. it is realy weird... on my mac it works too...

I'm finding more and more reasons why I should switch to native Linux and ditch Windows.
I think it could be because I have done a lot on the Windows PC and have changed the mods from time to time to test my version of certain packages. I have already deleted the mod cache but now well. I will call this a Windows problem in combination with Layer 8 issue ;-) 

Because on my Mac it is Running too. so i will close this Issue as a False Positive.

thank you for the fast answer and testing!

Best regards

**Comment by linux-china** [comment]
Same problem to me: 

```
../../go/pkg/mod/gofr.dev@v1.9.0/pkg/gofr/container/mock_container.go:27:20: cannot use redisMock (variable of type *MockRedis) as Redis value in assignment: *MockRedis does not implement Redis (missing method BitFieldRO)
```

Environments (please complete the following information):
Darwin  23.5.0 Darwin Kernel Version 23.5.0.  arm64 Apple M1 Pro

I did `go clean -modcache` and `go build` again, still got the same problem.

**Comment by AchimGrolimund** [comment]
hello @linux-china 

run the following: `git reset --hard origin/main`

In my case the error was that something crept in somewhere. I tend to think that something was cached somewhere (gomod git os) I got it running again on my Windows computer, which had this error, with the above command.

**Comment by AchimGrolimund** [comment]
@aryanmehrotra 
I was able to reproduce the error.
If you clone my above mentioned repository and run a `go mod -u ./...`, the following packages are updated (and many more):

```
go: upgraded github.com/redis/go-redis/extra/rediscmd/v9 v9.0.5 => v9.5.3
go: upgraded github.com/redis/go-redis/extra/redisotel/v9 v9.0.5 => v9.5.3
go: upgraded github.com/redis/go-redis/v9 v9.5.1 => v9.5.3
```
When I now try to start my application, the following appears: 
```bash
go run cmd/csp-scout-api/main.go 
# gofr.dev/pkg/gofr/container
..\..\..\..\go\pkg\mod\gofr.dev@v1.9.0\pkg\gofr\container\mock_container.go:27:20: cannot use redisMock (variable of type *MockRedis) as Redis value in assignment: *MockRedis does not implement Redis (missing method BitFieldRO) 
```


Solution:
go to the `go.mod` file and change the version of the `redis` packages back:

in my case:
```
	github.com/redis/go-redis/extra/rediscmd/v9 v9.0.5 // indirect
	github.com/redis/go-redis/extra/redisotel/v9 v9.0.5 // indirect
	github.com/redis/go-redis/v9 v9.5.1 // indirect
```

Run the app and it works.

CC/ @linux-china

**Comment by srijan-27** [comment]
@AchimGrolimund - The versions that you mentioned as the solution are the same which are being used in GoFr's go.mod, so it wouldn't be an issue if you use the same without upgrading to latest.
Also, IMO it is recommended to cautiously run `go mod -u ./...` as it may cause versions mismatch for direct and indirect dependencies.
