### ISSUE TITLE
Add support for YML migration files

### ISSUE THREAD

**Issue by max-chem-eng** [gofr-dev/gofr#758]
## Add support for writing migration files in yml
Abstracting the parameters for creating/updating tables to a simple yml file would make the code easier to read and maintain and reduces boilerplate code

**Comment by srijan-27** [comment]
The migrations are easily written in go itself as per the current implementation.
Reference: https://gofr.dev/docs/advanced-guide/handling-data-migrations

So, I believe adding an extra layer over migrations would not be a good thing to do.
