### ISSUE TITLE
Live/Hot Reloading when the environment is development

### ISSUE THREAD

**Issue by KedarisettiSreeVamsi** [gofr-dev/gofr#759]
**Is your feature request related to a problem? Please describe.**
Often times when we develop any application we like the possibility of having the application to go into debug mode and also reload if any changes takes place immediately.

**Describe the solution you'd like**
Hot reloading/ Live reloading helps in easing the development process.
Some of the repos which enable hot reloading are https://github.com/air-verse/air
https://github.com/gravityblast/fresh, etc.

**Describe alternatives you've considered**

**Additional context**

One such example where hot reloading is enabled is https://github.com/anthdm/superkit.

**Comment by iamgoroot** [comment]
This seems to be an external tooling. I don't see how it can be implemented inside of a library
Just run your code with respective commands in your terminal/IDE instead of `go run .`

**Comment by aryanmehrotra** [comment]
Exactly @iamgoroot this would not be part of the framework feature.
