### ISSUE TITLE
Fix too long time.Sleep in tests

### ISSUE THREAD

**Issue by ccoVeille** [gofr-dev/gofr#795]
> 2 seconds is too long for tests

_Originally posted by @ccoVeille in https://github.com/gofr-dev/gofr/pull/781#discussion_r1666561069_

> 3 seconds is like ages for tests

_Originally posted by @ccoVeille in https://github.com/gofr-dev/gofr/pull/781#discussion_r1666563213_

**Comment by srijan-27** [comment]
@ccoVeille - I believe this is fixed now as long sleep timers have been removed.
Let me know if you think anything is missed, or if this can be closed.

**Comment by ccoVeille** [comment]
I'm curious if we can see a difference in term of CI duration.

Before starting
After the time.Sleep fix
After the cronjob seconds patch

**Comment by srijan-27** [comment]
As per my observations, previously package and example tests were taking more than 2 mins and around 2 mins respectively.
But after the fixes, both the pipelines are running in around 1 min, which is 50% more optimised.
