### ISSUE TITLE
Versions `v1.14.0` logger Fatal got removed

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#841]
This is a breaking change it was not mentioned anywhere
https://github.com/gofr-dev/gofr/pull/839/files#diff-e92617e89e725475cdab2f53b02884b745512675e04db93dc2a732adb6b25f6b

**Comment by srijan-27** [comment]
@surajit-zs - this was removed in #801, and somehow missed while reviewing.
Fixing this now.. will make a patch release.

**Comment by ccoVeille** [comment]
My bad, I was not expecting it to be called outside the framework.

My bad, terrible mistake.

**Comment by ccoVeille** [comment]
Some explanation about the context

https://github.com/gofr-dev/gofr/pull/801#discussion_r1675745779
