### ISSUE TITLE
Add test about logger interface, especially Fatal

### ISSUE THREAD

**Issue by ccoVeille** [gofr-dev/gofr#844]
Fatal and Fatalf were removed from the logger and nothing caught they shouldn't be removed.

While this method are an anti pattern. They exists and should be tested.

The fact they are calling os.Exit(1) doesn't help to test them. But it's possible with a small refactoring maybe.

> Apparently, nothing was using it, and one of them implementation was doing a deep exit:
>
> Calling a os.Exit(1) in the code, slaughtering all the stacks and the possible defer, context cancelation.
>
> I missed people may use it by calling the framework

_Originally posted by @ccoVeille in https://github.com/gofr-dev/gofr/issues/841#issuecomment-2225437051_

**Comment by ccoVeille** [comment]
One solution could be to add an exiter, that can be overloaded for test 

```go
var exiter func() = func() { os.Exit(1)}

func(l *Logger) Fatal(args ...any) {
      l.logger.Log("fatal", args...)
      exiter()
}

func overloadExiter(t *testing.T, f func()) {
      exiter = f
      t.Cleanup(func(){
         exiter =func() { os.Exit(1) }
      })
}
```

This is pseudo code, just an idea, it can be improved

**Comment by srijan-27** [comment]
@ccoVeille - Yes, there should be tests for these methods.. although I was trying to add tests, but in the need of urgency to fix the broken release, I just went ahead with the fix. I'm looking into it, and will add the tests.

**Comment by ccoVeille** [comment]
Yes, of course.

BTW, I found a photo of me when I removed the methods 😱😬😁😅

![ikg6tlu1slcd1.jpeg](https://github.com/user-attachments/assets/6dbc95e0-d35f-4cd4-ba3c-872c123ec3e3)

**Comment by vipul-rawat** [comment]
> One solution could be to add an exiter, that can be overloaded for test
> 
> ```go
> var exiter func() = func() { os.Exit(1)}
> 
> func(l *Logger) Fatal(args ...any) {
>       l.logger.Log("fatal", args...)
>       exiter()
> }
> 
> func overloadExiter(t *testing.T, f func()) {
>       exiter = f
>       t.Cleanup(func(){
>          exiter =func() { os.Exit(1) }
>       })
> }
> ```
> 
> This is pseudo code, just an idea, it can be improved

Yes, we have to encapsulate the os.Exit() function! It is the only way to test for standard library functions.
```go
var exit = os.Exit

func (l *logger) Fatalf(format string, args ...interface{}) {
    l.logf(FATAL, format, args...)
    exit(1)
}


func overLoadExit(t *testing.T) {
    exit = func(i int){
    // can mock the exit code and/or assert them
    }

    t.Cleanup(func(){
        exit = os.Exit
    })
}

```

**Comment by srijan-27** [comment]
@vipul-rawat -  already tried this, but since we should not have global variables (here `exit), so didn't follow this approach, instead using subprocess to test this.
Reference: https://go.dev/talks/2014/testing.slide#23

**Comment by ccoVeille** [comment]
I will have a look at the link you shared.

But, I would recommend using an unexported exit struct variable in the logger, and when not overloaded. The code default to os.Exit

**Comment by ccoVeille** [comment]
Hey @xhd2015

What would you recommend to "mock" the os.Exit call ?

For everyone else, here is his interesting project
https://github.com/xhd2015/xgo

**Comment by ccoVeille** [comment]
> I will have a look at the link you shared.
> 
> But, I would recommend using an unexported exit struct variable in the logger, and when not overloaded. The code default to os.Exit

Here is what I suggested earlier looks alike

https://github.com/gofr-dev/gofr/pull/848#discussion_r1678962961

**Comment by xhd2015** [comment]
> Hey @xhd2015
> 
> What would you recommend to "mock" the os.Exit call ?
> 
> For everyone else, here is his interesting project https://github.com/xhd2015/xgo

Huh, perfectly stdlib can be mocked by xgo, without the need to change the source code.

```go
import "github.com/xhd2015/xgo/runtime/mock"

func TestSomethingCallingOSExit(t *testing.T){
    // this 'patch' only affects this test, the global os.Exit will remain unchanged
    var capturedCode int
    mock.Patch(os.Exit, func(code int) {
          capturedCode = code
   })
   somethingCallOsExit()
   if capturedCode != 1 {
        t.Fatalf("expect capturedCode=1, actual: %d", capturedCode)
   }
}

func somethingCallOsExit(){
     // ....
    os.Exit(1)
}
```


Test:
```sh
go install github.com/xhd2015/xgo/cmd/xgo@latest
xgo test
```

**Comment by vipul-rawat** [comment]
@xhd2015 Do we have to run the `xgo test` if we are using the xgo mock package, does this not work with the `go test` command?

**Comment by xhd2015** [comment]
> @xhd2015 Do we have to run the `xgo test` if we are using the xgo mock package, does this not work with the `go test` command?

Unfortunately yes. The go test alone cannot do mock itself.

**Comment by ccoVeille** [comment]
Oh, I missed that. Thanks @vipul-rawat 

It's indeed a limitation.
