### ISSUE TITLE
Enhance default logging to automatically log return errors

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#850]
When an error is returned, only the status code and correlation ID are logged, without the error message. This makes the logs less useful, as the reason for the error is not visible.

ref:
![image](https://github.com/user-attachments/assets/c41773ad-3619-4811-b7bc-0641ec2df9aa)

To get the error message, we are manually logging the error before returning it. However, this only logs the error message without additional context like the status code and correlation ID.

ref:
![image](https://github.com/user-attachments/assets/15cc87aa-79b2-40db-bdf5-b77a727d62c3)

Proposed Enhancement
It would be helpful if the system automatically logged errors by default, including:

Error message
Status code
Correlation ID

**Comment by aryanmehrotra** [comment]
Status code and Correlation ID are already present, we would be adding Error Message.

**Comment by vikash** [comment]
While we are doing this, we also need to ensure that all logs are also having the corresponding correlation ID with the line. Otherwise it will be difficult to track which error got generated during a given request lifecycle.

**Comment by aditya028** [comment]
@aryanmehrotra I would like to work on this issue. please assign it to me

**Comment by srijan-27** [comment]
@aditya028 - Sure, assigning this to you.

**Comment by aditya028** [comment]
<img width="697" alt="Screenshot 2024-07-29 at 5 07 32 PM" src="https://github.com/user-attachments/assets/60a8889d-58f6-4bc1-a0d8-5b8316a3f2af">

will it look something like this after the error log @srijan-27

**Comment by srijan-27** [comment]
@aditya028 - Yes, this would be the expected behaviour.

**Comment by srijan-27** [comment]
@aditya028 - Are you working on it? Please let me know if you need any help.

**Comment by aditya028** [comment]
> @aditya028 - Are you working on it? Please let me know if you need any help.

@srijan-27 Yes i am working on it and will  update the PR this weekand
