### ISSUE TITLE
Unsupported trace exporter

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#851]
When the environment variable TRACER_URL is set but TRACE_EXPORTER I forget to add, the following error message is generated:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/381964d0-f250-4a23-ab6d-55cea3fe77ec">

I would suggest that you add the error message to indicate that the TRACE_EXPORTER environment variable is missing.

**Comment by Sianao** [comment]
I'm working on  it  [#856](https://github.com/gofr-dev/gofr/pull/856)

**Comment by srijan-27** [comment]
@Sianao - Thanks for your contribution, but since this was already assigned so the work is in progress for the ticket.
You can refer branch: https://github.com/gofr-dev/gofr/tree/fix/tracer-config-validation
