### ISSUE TITLE
Issue: Failed to load config from file: ./configs/.env, Err: unexpected character

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#852]
Currently, the framework gives a warning error when the .env file contains some invalid characters and proceeds to start the servers without taking any configuration from the .env file. This behavior can lead to significant issues, especially in production.

If a new build inadvertently includes an invalid env, the server will start, leading to various problems due to missing or incorrect configurations. To mitigate this risk, the application should not start if the .env file is present and contains errors. This will ensure that new pods do not come up with incorrect configurations.

ref:<img width="1347" alt="image" src="https://github.com/user-attachments/assets/2b1d8924-e61f-4265-97ae-49986a5bc76f">

**Comment by srijan-27** [comment]
@surajit-zs - Yes, this should be the expected behaviour. Will update it to not start application in case of any issues.
