### ISSUE TITLE
Cen't connect to neon Postgres (sslmode=require)

### ISSUE THREAD

**Issue by m4rcelpl** [gofr-dev/gofr#870]
**Describe the bug**
When I try to set up a connection to Postgres, I receive an error:

error: pq: connection is insecure (try using `sslmode=require`)

**To Reproduce**
Try configuring a connection to a database like Neon DB.
https://neon.tech/home

1. The code is

LOG_LEVEL=debug
DB_HOST='ep-XXXXXXXX.aws.neon.tech'
DB_USER=XXXXX
DB_PASSWORD=XXXXXX
DB_NAME=XXXXXX
DB_PORT=5432
DB_DIALECT=postgres

2. The error is

   ```
   error: pq: connection is insecure (try using `sslmode=require`)
   ```

**Screenshots**
<img width="1536" alt="Zrzut ekranu 2024-07-23 o 15 55 35" src="https://github.com/user-attachments/assets/e1cb5f92-88d0-426a-984f-fbbf5dbcbbe8">

**Environments (please complete the following information):**
- OS: MacoOS
- gofr version [e.g. v1.15.0]
- go version [e.g. 1.22.5]

**Comment by srijan-27** [comment]
@m4rcelpl - Thanks for reporting this issue.
By default, `sslmode` is set to `disable`, refer: https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/sql/sql.go#L179
Will need to look into the requirement and update as per needed.
