### ISSUE TITLE
Support for Query Parameters with Multiple Values

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#874]
### Description:
I would like to request support for handling query parameters that have multiple values. This feature is particularly useful in scenarios where a single parameter needs to accept an array of values, such as filtering search results by multiple categories or tags.

### Use Case:
In scenarios where users need to filter or search with multiple criteria, it's common to use the same query parameter name with different values. For example:

Copy code
```bash
 /api/search?category=books&category=electronics
```
This syntax allows for a clean and intuitive way to pass multiple values for a single key, and it is supported by many web frameworks and libraries.

### Current Behavior:
Currently, the application does not support query parameters with multiple values, and only the last provided value is considered.

### Desired Behavior:
The application should support query parameters with multiple values, and the values should be accessible as an array or list. For example, the query parameters in the request /api/search?category=books&category=electronics should be parsed into an array like ["books", "electronics"].

### Proposed Solution:
Update the query parameter parsing logic to handle multiple values for the same key.
Ensure that the values are accessible as an array or list in the backend.
Update the documentation to reflect this new capability.

Ref:
```go
package main

import (
    "fmt"
    "log"
    "net/http"
)

func searchHandler(w http.ResponseWriter, r *http.Request) {
    categories := r.URL.Query()["category"]
    fmt.Fprintf(w, "Categories: %v\n", categories)
    log.Println("Categories:", categories)
}

func main() {
    http.HandleFunc("/api/search", searchHandler)
    log.Println("Server running on port 8080")
    log.Fatal(http.ListenAndServe(":8080", nil))
}

```

```curl
curl --location 'http://localhost:8080/api/search?category=books&category=electronics'
```

**Comment by srijan-27** [comment]
@surajit-zs - Thanks for reporting the issue. I agree this should be the supported in framework, will look for the appropriate solution.
