### ISSUE TITLE
Support for writing response without returning from WebSocket handler

### ISSUE THREAD

**Issue by shashank-zopsmart** [gofr-dev/gofr#881]
**Current Behaviour**
- In order to send response to client, we need to return values, from the WebSocket handler. 
- This means that client will again have to make request to get response (if it needs again).
- There can be case when WebSocket handler needs to write response multiple times without having the client need to make request again (as WebSocket provides a simultaneous two-way communication channel over a single connection).

**Expected Behaviour**
- There should be some exposed method in `Context` so that response can be written without having to return values from the handlers.

**Comment by Umang01-hash** [comment]
Thankyou for mentioning the issue. Will take it up.
