### ISSUE TITLE
Bug: mongo debug logs are not structured in json format

### ISSUE THREAD

**Issue by vipul-rawat** [gofr-dev/gofr#882]
**Describe the bug**
The DEBUG logs for Mongo datasource are not in proper JSON format, the `message` field is a string where it should be a nested object.

**To Reproduce**
Run any Mongo application with DEBUG mode and logs not going to the terminal.

**Expected behaviour**
The logs should have a proper JSON structure when not printed on a terminal.

**Environments (please complete the following information):**
- OS: Darwin
- gofr version: v1.15.0
- go version: 1.22

**Comment by coolwednesday** [comment]
@vipul-rawat Please assign this issue to me.
