### ISSUE TITLE
How to make primary key autoincrement in postgres

### ISSUE THREAD

**Issue by Naveenbhargav-Mallampati** [gofr-dev/gofr#888]
```
type users struct {
	Id         int    `json:"id" gofr:"primary_key,auto_increment"`
	Name       string `json:"name"`
	Age        int    `json:"age"`
	IsEmployed bool   `json:"isEmployed"`
}
```

I have added a addRestHandler for this struct.
cruds are working fine.

The only problem is , in create api --> without passing id : first time creates and row with 0 id , after that , it is returning postgres deplicate id contraint voliation error.

when create if we pass id explicitly it is working.

in Auto cruds , is there a way to make id autoincrement in any way.

sorry if it is a silly  question.

**Comment by aryanmehrotra** [comment]
Yes, it will be supported. It is work in progress in PR830
