### ISSUE TITLE
Error logs are not printed in the file.

### ISSUE THREAD

**Issue by coolwednesday** [gofr-dev/gofr#904]
**Describe the bug**
Error logs are not printed in the file.
<img width="1440" alt="Screenshot 2024-08-06 at 12 36 23 PM" src="https://github.com/user-attachments/assets/56bead68-a63a-43bf-bfeb-28dcd527f8b5">

**To Reproduce**
Steps to reproduce the behaviour, if applicable:
Connect to any datasource or feature that uses print logs.
Direct all the logs to a text file.
You will notice that in case there is an error..it is not written to the file, but instead gets printed on the terminal.

**Comment by srijan-27** [comment]
@coolwednesday - Thanks for pointing this out.
Although this is not an issue from framework. While running the command, you should use `&>` instead of `>>` or `>` to publish logs in the given file.
