### ISSUE TITLE
unsupported TRACE_EXPORTER: 

### ISSUE THREAD

**Issue by surajit-zs** [gofr-dev/gofr#909]
<img width="807" alt="image" src="https://github.com/user-attachments/assets/db22aca8-9066-44d8-b9a3-a2df77137210">

After updating the gofr version to v1.16.0, we're encountering the following error: unsupported TRACE_EXPORTER:. We're not using any tracing, and the environment variables are empty. Could you please look into this issue?

**Comment by srijan-27** [comment]
@surajit-zs - Thanks for reporting this issue.
This was already know, and the PR #901 was created and pending for merge.
