### ISSUE TITLE
Support ReadDir, ChDir and Stat to perform Dir related operations

### ISSUE THREAD

**Issue by vipul-rawat** [gofr-dev/gofr#919]
Currently, the filesystem does not have the reading the directory functionality to find information about the directory contents, similar to os.ReadDir()

Edit: Found some more missing functions that could be useful in a fileSystem - ChDir(to change the dir), Stat(to retrieve information about a file or dir)

**Comment by coolwednesday** [comment]
@vipul-rawat Please, assign the issue to me.

**Comment by Umang01-hash** [comment]
> @vipul-rawat Please, assign the issue to me.

Assigned!
