### ISSUE TITLE
Fix Pipeline for external datasources

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#964]
Linters and tests are not running for external datasources as they are different modules.
Need to check if the current command can be changed somehow to incorporate it or we need to run them separately.

**Comment by coolwednesday** [comment]
To fix the pipeline :
- We wish to fix it in multiple PRs to first fix the datasources (linters & tests)
- Introducing new workflow to run tests and linters in datasources also.

**Comment by Umang01-hash** [comment]
@coolwednesday assigned the issue to you.
