### ISSUE TITLE
Improper logs  in sqlite db

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#968]
When connecting to sqlite db - logs are coming incorrectly.

Port and host are coming in spite of no port and host required.

To Reproduce: Connect with the following configs - 
DB_DIALECT=sqlite
DB_NAME=test

**Comment by SkMishra77** [comment]
Hi @aryanmehrotra I would like to work on this. Could your please Assign this issue to me?

**Comment by SkMishra77** [comment]
@aryanmehrotra are you referring to this line in log 
,"message":"connected to 'test_db' database at 'localhost:3306'"

here ip:port should not be logged for sqlite

**Comment by aryanmehrotra** [comment]
Yes and if you can set log level to DEBUG you would be seeing more of these

**Comment by SkMishra77** [comment]
ok so for sqlite only changing it to **connected to 'test_db' database**

**Comment by Umang01-hash** [comment]
@SkMishra77 yups you can raise a PR for these changes

**Comment by SkMishra77** [comment]
@aryanmehrotra @Umang01-hash 
Code Climate fails because Cognitive Complexity exceeds so should i refactor this fuction ?

**Comment by coolwednesday** [comment]
@Umang01-hash , I see the linked PR has no latest progress. I would like to work on this. Please assign this to me.
