### ISSUE TITLE
How to mock `ctx.SQL.QueryRow(...)`

### ISSUE THREAD

**Issue by dwivedisshyam** [gofr-dev/gofr#970]
I'm using QueryRow function to select a single row from the database. But unable to mock it. The method returns an object of `sql.Row` type but couldn't find a way to mock it.
```go
q := `SELECT id, name, email, address, icon, is_active, created_at, updated_at FROM organizations WHERE id=? AND is_active=?`

row := ctx.SQL.QueryRow(q, orgId, true)
```

@aryanmehrotra

**Comment by aryanmehrotra** [comment]
Hey, we have reported this bug, and we are tracking it here, it is due to the additional methods we have an interface.
We would fix it ASAP.
https://github.com/gofr-dev/gofr/issues/960
