### ISSUE TITLE
Create DOCKERFILE for examples - with observability setup

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#989]
Currently, DOCKERFILE are not present for examples - observability is needed to be setup manually.

Docker files needs to be added with observability setup.

**Comment by vigneshp91** [comment]
Do you want to add the docker setup for observability in 
/examples/http-server folder?  or in any specific example @aryanmehrotra

**Comment by aryanmehrotra** [comment]
It would be similar for all of those - but let's first add for http-server

**Comment by vigneshp91** [comment]
@aryanmehrotra Can you assign this to me?
