### ISSUE TITLE
Incorrect overview for container package

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#991]
Incorrect overview for container package
<img width="925" alt="Screenshot 2024-09-06 at 11 38 52 PM" src="https://github.com/user-attachments/assets/b2c33f39-4044-4c4f-b56b-9fcb8ffa59a0">

**Comment by aryanmehrotra** [comment]
Hey @JonasBakys0 we would to make it more suitable.

**Comment by JonasBakys0** [comment]
Cool, can I try it? Can you assign me to this issue?
