### ISSUE TITLE
Refactor BasicAuthMiddleware

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#996]
Function BasicAuthMiddleware has a Cognitive Complexity of 19 (exceeds 12 allowed).

Refer : https://codeclimate.com/github/gofr-dev/gofr/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by kuldeep-bishnoi** [comment]
Hi @aryanmehrotra 
I would like to work on this issue. Could you please assign it to me?

**Comment by srijan-27** [comment]
@kuldeep-bishnoi - This is already assigned to @iamshubha, so can't assign this to you as of now.. if Shubha doesn't pick this up then maybe you can work on this.

**Comment by vipul-rawat** [comment]
@iamshubha Are you working on this, Please raise a PR or we would have to unassign this issue.

**Comment by Umang01-hash** [comment]
@iamshubha unassigning the issue to you because of unactiveness and no reply.

@kuldeep-bishnoi would you like to work on it ?

**Comment by nidhey27** [comment]
@Umang01-hash I've refactored the BasicAuthMiddleware function to reduce its cognitive complexity. When you have a moment, could you please review the changes? I’d appreciate any feedback on the refactor or suggestions for further improvement.

**Comment by Umang01-hash** [comment]
Sure @nidhey27 we will review it and let you know about any changes if needed.

**Comment by nidhey27** [comment]
@Umang01-hash do you guys have slack channel or anything for communication with maintainer?

**Comment by nidhey27** [comment]
Cool 👍
